import type { Metadata } from "next";
import Link from "next/link";
import { connection } from "next/server";
import { notFound, redirect } from "next/navigation";
import { IdentityError, requireRole } from "@/lib/identity";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getStaffBooking, getStaffHistory, getStaffTables, staffStatusLabel, formatBookingDate } from "@/lib/staff-operations";
import { StaffActionPanel } from "@/components/staff-action-panel";
export const metadata: Metadata = { title: "Chi tiết booking Staff", robots: { index: false, follow: false } };
export function generateStaticParams(): { id: string }[] { return [{ id: "preview" }]; }
export default async function StaffBookingDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const demo = process.env.NEXT_PUBLIC_STATIC_DEMO === "true"; const { id } = await params; if (demo) return <section className="section"><div className="site-container staff-container"><p className="eyebrow">Staff operations</p><h1>Chi tiết booking.</h1><p className="lead">Bản demo tĩnh không đọc dữ liệu vận hành.</p><Link className="button button-secondary" href="/">Về trang chính</Link></div></section>;
  await connection(); try { await requireRole(["staff", "admin"]); } catch (error) { if (error instanceof IdentityError && error.status === 401) redirect("/login"); if (!(error instanceof IdentityError) || error.status === 503) throw error; return <section className="section"><div className="site-container staff-container"><h1>Không có quyền truy cập.</h1><p className="booking-error" role="alert">Chỉ tài khoản Staff hoặc Admin mới có thể sử dụng khu vực này.</p></div></section>; }
  const supabase = await createSupabaseServerClient(); const [booking, tables] = await Promise.all([getStaffBooking(supabase, id), getStaffTables(supabase)]); if (!booking) notFound(); const history = await getStaffHistory(supabase, id);
  return <section className="section"><div className="site-container staff-container"><Link className="back-link" href="/staff">← Danh sách vận hành</Link><div className="booking-detail-heading"><div><p className="eyebrow">Staff · Chi tiết booking</p><h1>{booking.contact_name}.</h1><p className="lead">{formatBookingDate(booking.starts_at)} · {booking.guest_count} khách</p></div><span className={`status status-${booking.status}`}>{staffStatusLabel(booking.status)}</span></div><div className="booking-detail-grid"><section className="booking-detail-section" aria-labelledby="staff-info-title"><h2 id="staff-info-title">Thông tin cuộc hẹn.</h2><dl className="booking-facts"><div><dt>Mã booking</dt><dd>{booking.id}</dd></div><div><dt>Bàn</dt><dd>{booking.table ? `${booking.table.code} · sức chứa ${booking.table.capacity}` : "Đang cập nhật"}</dd></div><div><dt>Khách thực tế</dt><dd>{booking.actual_guest_count ?? "Chưa check-in"}</dd></div><div><dt>Nguồn</dt><dd>{booking.source}</dd></div><div><dt>Điện thoại</dt><dd>{booking.contact_phone}</dd></div><div><dt>Email</dt><dd>{booking.contact_email || "Khách vãng lai"}</dd></div><div><dt>Ghi chú</dt><dd>{booking.notes || "Không có"}</dd></div></dl><StaffActionPanel bookingId={booking.id} status={booking.status} tableId={booking.table_id} tables={tables.map((table) => ({ id: table.id, code: table.code, capacity: table.capacity, status: table.status }))} /></section><section className="booking-detail-section" aria-labelledby="staff-history-title"><h2 id="staff-history-title">Lịch sử xử lý.</h2>{history.length ? <ol className="booking-history">{history.map((event) => <li key={event.id}><p className="meta-line">{formatBookingDate(event.created_at)}</p><p>{event.from_status ? `${staffStatusLabel(event.from_status)} → ` : ""}{staffStatusLabel(event.to_status)}</p><span>{event.source === "staff" ? "Nhân viên" : event.source === "system" ? "Hệ thống" : "Khách"}{event.reason ? ` · ${event.reason}` : ""}</span></li>)}</ol> : <p className="empty-state">Chưa có lịch sử.</p>}</section></div></div></section>;
}
