import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { FloorPlan } from "@/components/floor-plan";
import { MediaPlaceholder } from "@/components/media-placeholder";
import { getFloor, restaurantFloors } from "@/data/restaurant";
type FloorPageProps = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return restaurantFloors.map((floor) => ({ slug: floor.slug })); }
export async function generateMetadata({ params }: FloorPageProps): Promise<Metadata> { const floor = getFloor((await params).slug); return floor ? { title: `Tầng ${floor.level} · ${floor.name}`, description: floor.description } : {}; }
export default async function FloorPage({ params }: FloorPageProps) { const floor = getFloor((await params).slug); if (!floor) notFound(); const capacity = floor.tables.reduce((total, table) => total + table.capacity, 0); return <><section className="floor-hero"><div className="site-container floor-hero-grid"><div><Link className="back-link" href="/spaces">← Tất cả không gian</Link><p className="eyebrow">Tầng {floor.level} · {floor.tables.length} bàn · {capacity} chỗ</p><h1>{floor.name}</h1><p className="lead">{floor.description}</p><ul className="feature-list">{floor.features.map((feature) => <li key={feature}>{feature}</li>)}</ul></div><MediaPlaceholder kind="space" label={`Hero Tầng ${floor.level} · ${floor.name}`} /></div></section><main className="section"><div className="site-container"><FloorPlan floor={floor} /><section className="floor-details"><div><p className="eyebrow">Danh sách bàn</p><h2>{floor.tables.length} bàn trong {floor.name}</h2><div className="table-list">{floor.tables.map((table) => <article key={table.code}><strong>{table.code}</strong><span>{table.capacity} chỗ</span><p>{table.position}{table.note ? ` · ${table.note}` : ""}</p></article>)}</div></div><div className="isometric-block"><MediaPlaceholder kind="isometric" label={`Minh họa isometric Tầng ${floor.level} · ${floor.name}`} /><p>Minh họa isometric sẽ dùng cùng logic bố trí với sơ đồ bàn, không thay thế sơ đồ tương tác.</p></div></section><div className="floor-cta"><div><p className="eyebrow">Bước tiếp theo</p><h2>Khám phá menu trước khi chọn bàn.</h2></div><Link className="button button-primary" href="/menu">Xem thực đơn</Link></div></div></main></>; }
