import { NextRequest, NextResponse } from "next/server";
import { IdentityError, requireRole } from "@/lib/identity";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getApplicationOrigin } from "@/lib/supabase/origin";
import { bookingError } from "@/lib/booking";
const headers = { "Cache-Control": "private, no-store" }; const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; const actions = ["confirm", "reject", "cancel", "check_in", "no_show", "complete", "move"] as const;
export async function POST(request: NextRequest) {
  if (request.headers.get("origin") !== getApplicationOrigin(request)) return NextResponse.json({ message: "Yêu cầu không hợp lệ." }, { status: 403, headers });
  if (!request.headers.get("content-type")?.startsWith("application/json")) return NextResponse.json({ message: "Yêu cầu cần định dạng JSON." }, { status: 415, headers });
  try {
    const { user } = await requireRole(["staff", "admin"]); const raw = await request.text(); if (raw.length > 8192) return NextResponse.json({ message: "Yêu cầu quá dài." }, { status: 413, headers }); const body: unknown = JSON.parse(raw); if (!body || typeof body !== "object" || Array.isArray(body)) return NextResponse.json({ message: "Dữ liệu không hợp lệ." }, { status: 400, headers }); const fields = body as Record<string, unknown>; const id = fields.id; const action = fields.action;
    if (typeof id !== "string" || !uuid.test(id) || typeof action !== "string" || !(actions as readonly string[]).includes(action)) return NextResponse.json({ message: "Booking hoặc thao tác không hợp lệ." }, { status: 400, headers });
    const reason = typeof fields.reason === "string" ? fields.reason.trim() : ""; if (["reject", "cancel", "no_show", "move"].includes(action) && (!reason || reason.length > 500)) return NextResponse.json({ message: "Thao tác này cần lý do tối đa 500 ký tự." }, { status: 400, headers }); const actualGuestCount = fields.actualGuestCount === undefined || fields.actualGuestCount === null ? null : Number(fields.actualGuestCount); if (actualGuestCount !== null && (!Number.isInteger(actualGuestCount) || actualGuestCount < 1 || actualGuestCount > 8)) return NextResponse.json({ message: "Số khách thực tế không hợp lệ." }, { status: 400, headers });
    const supabase = await createSupabaseServerClient(); let data: unknown; let error: { code?: string; message?: string } | null = null;
    if (action === "move") { if (typeof fields.newTableId !== "string" || !uuid.test(fields.newTableId)) return NextResponse.json({ message: "Bàn mới không hợp lệ." }, { status: 400, headers }); ({ data, error } = await supabase.rpc("staff_move_booking", { p_id: id, p_new_table_id: fields.newTableId, p_reason: reason })); } else ({ data, error } = await supabase.rpc("staff_update_booking", { p_id: id, p_action: action, p_reason: reason || null, p_actual_guest_count: actualGuestCount }));
    if (error) { const result = bookingError(error); const messages: Record<string, string> = { REASON_REQUIRED: "Hãy nhập lý do.", PENDING_EXPIRED: "Booking đã hết thời gian chờ xác nhận.", CHECKIN_TOO_EARLY: "Chưa đến thời gian check-in.", CHECKIN_TOO_LATE: "Đã quá thời gian check-in; hãy xử lý không đến.", TABLE_NOT_READY: "Bàn chưa sẵn sàng.", NO_SHOW_TOO_EARLY: "Chưa đủ điều kiện đánh dấu không đến.", MOVE_NOT_ALLOWED: "Chỉ có thể đổi bàn cho booking đã xác nhận chưa check-in.", BOOKING_CONFLICT: "Bàn mới đang vướng lịch khác." }; return NextResponse.json({ message: messages[error.message ?? ""] ?? result.message }, { status: error.code === "42501" ? 403 : error.message === "BOOKING_NOT_FOUND" ? 404 : 409, headers }); }
    return NextResponse.json({ bookingId: Array.isArray(data) ? data[0]?.id : (data as { id?: string } | null)?.id, action, actor: user.id }, { headers });
  } catch (error) { if (error instanceof IdentityError) return NextResponse.json({ message: error.status === 401 ? "Vui lòng đăng nhập tài khoản Staff." : "Tài khoản không có quyền vận hành." }, { status: error.status, headers }); if (error instanceof SyntaxError) return NextResponse.json({ message: "JSON không hợp lệ." }, { status: 400, headers }); return NextResponse.json({ message: "Chưa thể hoàn tất thao tác. Vui lòng thử lại." }, { status: 503, headers }); }
}
