"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent, type ReactNode } from "react";
import type { AdminAudit, AdminSettings, AdminSnapshot } from "@/lib/admin";

type Props = { snapshot: AdminSnapshot; range: { from: string; to: string }; combosEnabled?: boolean };
type FormValues = Record<string, FormDataEntryValue>;

function stringValue(form: FormData, key: string) { return String(form.get(key) ?? "").trim(); }
function booleanValue(form: FormData, key: string) { return form.get(key) === "on"; }
function numberValue(form: FormData, key: string) { return Number(stringValue(form, key)); }
function RowForm({ action, expectedValues, onSubmit, children, busy = false }: { busy?: boolean; action: string; expectedValues: Record<string, unknown>; onSubmit: (event: FormEvent<HTMLFormElement>, action: string, expectedValues: Record<string, unknown>) => void; children: ReactNode }) {
  return <form key={JSON.stringify(expectedValues)} className="admin-row-form" onSubmit={(event) => onSubmit(event, action, expectedValues)}>{children}<label>Lý do thay đổi<input name="reason" required maxLength={500} placeholder="Ví dụ: cập nhật policy Phần 8" /></label><button className="button button-secondary" type="submit" disabled={busy}>Lưu</button></form>;
}

function Section({ eyebrow, title, note, children }: { eyebrow: string; title: string; note?: string; children: ReactNode }) {
  return <section className="admin-section"><div className="admin-section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{note && <p className="section-note">{note}</p>}</div>{children}</section>;
}

function TableWrap({ children }: { children: ReactNode }) { return <div className="admin-table-wrap"><table className="admin-table">{children}</table></div>; }

function policyExpected(settings: AdminSettings) {
  return { name: settings.name, duration_minutes: settings.duration_minutes, buffer_minutes: settings.buffer_minutes, min_notice_minutes: settings.min_notice_minutes, max_advance_days: settings.max_advance_days, pending_minutes: settings.pending_minutes, cancellation_minutes: settings.cancellation_minutes, early_checkin_minutes: settings.early_checkin_minutes, no_show_minutes: settings.no_show_minutes, max_active_bookings: settings.max_active_bookings, max_guests: settings.max_guests };
}

export function AdminConsole({ snapshot, range, combosEnabled = false }: Props) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [messageIsError, setMessageIsError] = useState(false);
  const [search, setSearch] = useState("");
  const [profileSearch, setProfileSearch] = useState("");
  const [profilePage, setProfilePage] = useState(0);

  async function onSubmit(event: FormEvent<HTMLFormElement>, action: string, expectedValues: Record<string, unknown>) {
    event.preventDefault();
    if (busy) return;
    if (action === "profile" && !window.confirm("Xác nhận thay đổi quyền hoặc trạng thái tài khoản này?")) return;
    setBusy(true); setMessage("");
    const form = new FormData(event.currentTarget); const values: FormValues = Object.fromEntries(form.entries());
    const payload: Record<string, unknown> = { action, expected: expectedValues, reason: stringValue(form, "reason") };
    for (const [key, value] of Object.entries(values)) if (key !== "reason") payload[key] = value;
    if (["settings"].includes(action)) {
      payload.durationMinutes = numberValue(form, "durationMinutes"); payload.bufferMinutes = numberValue(form, "bufferMinutes"); payload.minNoticeMinutes = numberValue(form, "minNoticeMinutes"); payload.maxAdvanceDays = numberValue(form, "maxAdvanceDays"); payload.pendingMinutes = numberValue(form, "pendingMinutes"); payload.cancellationMinutes = numberValue(form, "cancellationMinutes"); payload.earlyCheckinMinutes = numberValue(form, "earlyCheckinMinutes"); payload.noShowMinutes = numberValue(form, "noShowMinutes"); payload.maxActiveBookings = numberValue(form, "maxActiveBookings"); payload.maxGuests = numberValue(form, "maxGuests");
    }
    if (action === "hours-upsert") payload.weekday = numberValue(form, "weekday");
    if (["area", "table", "category", "menu-item", "profile"].includes(action)) {
      if (action === "area") payload.isActive = booleanValue(form, "isActive");
      if (action === "table") { payload.capacity = numberValue(form, "capacity"); payload.isActive = booleanValue(form, "isActive"); }
      if (action === "category") { payload.sortOrder = numberValue(form, "sortOrder"); payload.isActive = booleanValue(form, "isActive"); }
      if (action === "menu-item") { payload.price = numberValue(form, "price"); payload.isAvailable = booleanValue(form, "isAvailable"); payload.isActive = booleanValue(form, "isActive"); payload.isFeatured = booleanValue(form, "isFeatured"); payload.sortOrder = numberValue(form, "sortOrder"); payload.imagePath = stringValue(form, "imagePath") || null; }
      if (action === "profile") payload.isActive = booleanValue(form, "isActive");
    }
    try {
      const response = await fetch("/api/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json() as { message?: string };
      if (!response.ok) throw new Error(result.message ?? "Không thể lưu thay đổi.");
      setMessage("Đã lưu thay đổi. Dữ liệu đang được tải lại."); setMessageIsError(false); router.refresh();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể lưu thay đổi."); setMessageIsError(true); }
    finally { setBusy(false); }
  }

  async function deleteRow(action: string, values: Record<string, unknown>) {
    if (busy || !window.confirm("Xác nhận xóa lịch này? Booking đã có không tự bị hủy.")) return;
    const reason = window.prompt("Nhập lý do xóa lịch:");
    if (!reason?.trim()) return;
    setBusy(true); setMessage("");
    try {
      const response = await fetch("/api/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...values, reason: reason.trim() }) });
      const result = await response.json() as { message?: string };
      if (!response.ok) throw new Error(result.message ?? "Không thể xóa.");
      setMessage("Đã lưu thay đổi."); setMessageIsError(false); router.refresh();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể xóa."); setMessageIsError(true); }
    finally { setBusy(false); }
  }

  const { settings, hours, closures, areas, tables, categories, menuItems, profiles, audits, bookings } = snapshot;
  const tableById = new Map(tables.map((table) => [table.id, table]));
  const areaById = new Map(areas.map((area) => [area.id, area]));
  const filteredItems = menuItems.filter((item) => `${item.code} ${item.name}`.toLocaleLowerCase("vi").includes(search.toLocaleLowerCase("vi")));
  const filteredProfiles = profiles.filter((profile) => `${profile.full_name} ${profile.phone ?? ""} ${profile.role}`.toLocaleLowerCase("vi").includes(profileSearch.toLocaleLowerCase("vi")));
  const byStatus = new Map<string, number>(); const bySource = new Map<string, number>(); const byFloor = new Map<string, number>(); const byDay = new Map<string, number>();
  for (const booking of bookings) { byStatus.set(booking.status, (byStatus.get(booking.status) ?? 0) + 1); bySource.set(booking.source, (bySource.get(booking.source) ?? 0) + 1); const floor = tableById.get(booking.table_id)?.area_id ?? "--"; byFloor.set(floor, (byFloor.get(floor) ?? 0) + 1); const day = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh" }).format(new Date(booking.starts_at)); byDay.set(day, (byDay.get(day) ?? 0) + 1); }
  return <section className="section"><div className="site-container admin-container"><header className="admin-header"><div><p className="eyebrow">Admin management · {settings.timezone}</p><h1>Điều hành bằng dữ liệu.</h1><p className="lead">Một nơi để cập nhật policy, catalogue, mặt bằng và quyền truy cập. Mọi thay đổi đều được kiểm soát và lưu lịch sử.</p></div><div className="admin-header-links"><Link className="back-link" href="/staff">Mở vận hành Staff ↗</Link><Link className="back-link" href="/">Về trang chính ↗</Link></div></header>
    <div className="admin-live-note" role="status"><strong>Dữ liệu live:</strong> bản Vercel đọc Supabase sau mỗi request. GitHub Pages vẫn là snapshot canonical, không gọi Admin API.</div>
    {combosEnabled && <p><Link className="text-link" href="/admin/combos">Quản lý combo ↗</Link></p>}
    <p className="admin-message" role={messageIsError ? "alert" : "status"} aria-live="polite">{busy ? "Đang lưu thay đổi…" : message}</p>
    <Section eyebrow="Tổng quan" title="Booking trong khoảng đã chọn" note="Số lượng booking, không phải doanh thu hay tỷ lệ lấp đầy."><form className="admin-range-form" method="get"><label>Từ ngày<input type="date" name="from" defaultValue={range.from} /></label><label>Đến ngày<input type="date" name="to" defaultValue={range.to} /></label><button className="button button-secondary" type="submit">Xem báo cáo</button></form><div className="admin-summary-line"><p><strong>{bookings.length}</strong> booking · {range.from} → {range.to}</p><p><strong>{profiles.filter((profile) => profile.is_active).length}</strong> tài khoản active · <strong>{tables.filter((table) => table.is_active).length}</strong> bàn active</p></div><div className="admin-report-grid"><div><h3>Theo ngày</h3><ul>{[...byDay].map(([key, value]) => <li key={key}><span>{key}</span><strong>{value}</strong></li>)}</ul></div><div><h3>Theo trạng thái</h3><ul>{[...byStatus].map(([key, value]) => <li key={key}><span>{key}</span><strong>{value}</strong></li>)}</ul></div><div><h3>Theo nguồn</h3><ul>{[...bySource].map(([key, value]) => <li key={key}><span>{key}</span><strong>{value}</strong></li>)}</ul></div><div><h3>Theo tầng</h3><ul>{[...byFloor].map(([key, value]) => <li key={key}><span>{areaById.get(key)?.name ?? key}</span><strong>{value}</strong></li>)}</ul></div></div></Section>
    <Section eyebrow="Chính sách" title="Cấu hình đặt bàn" note="Timezone cố định Asia/Ho_Chi_Minh. Thay đổi không tự hủy hoặc tính lại booking cũ."><RowForm action="settings" expectedValues={policyExpected(settings)} onSubmit={onSubmit} busy={busy}><div className="admin-form-grid"><label>Tên hệ thống<input name="name" defaultValue={settings.name} maxLength={120} required /></label>{([["durationMinutes", "Thời lượng (phút)", settings.duration_minutes], ["bufferMinutes", "Buffer (phút)", settings.buffer_minutes], ["minNoticeMinutes", "Báo trước tối thiểu", settings.min_notice_minutes], ["maxAdvanceDays", "Đặt trước tối đa (ngày)", settings.max_advance_days], ["pendingMinutes", "Pending (phút)", settings.pending_minutes], ["cancellationMinutes", "Hủy trước (phút)", settings.cancellation_minutes], ["earlyCheckinMinutes", "Check-in sớm (phút)", settings.early_checkin_minutes], ["noShowMinutes", "No-show sau (phút)", settings.no_show_minutes], ["maxActiveBookings", "Booking active tối đa", settings.max_active_bookings], ["maxGuests", "Số khách tối đa", settings.max_guests]] as const).map(([name, label, value]) => <label key={name}>{label}<input name={name} type="number" min={0} defaultValue={value} required /></label>)}</div></RowForm></Section>
    <Section eyebrow="Lịch phục vụ" title="Giờ mở cửa và ngày nghỉ" note="Khung giờ cùng ngày không được chồng lấn; xóa lịch yêu cầu xác nhận và lý do."><div className="admin-list">{hours.map((hour) => <div className="admin-list-row" key={hour.id}><RowForm action="hours-upsert" expectedValues={{ weekday: hour.weekday, opens_at: hour.opens_at, closes_at: hour.closes_at }} onSubmit={onSubmit} busy={busy}><input type="hidden" name="id" value={hour.id} /><label>Thứ<select name="weekday" defaultValue={hour.weekday}>{[0, 1, 2, 3, 4, 5, 6].map((day) => <option key={day} value={day}>{day === 0 ? "Chủ nhật" : `Thứ ${day + 1}`}</option>)}</select></label><label>Mở cửa<input name="opensAt" type="time" defaultValue={hour.opens_at.slice(0, 5)} required /></label><label>Đóng cửa<input name="closesAt" type="time" defaultValue={hour.closes_at.slice(0, 5)} required /></label></RowForm><button className="button button-quiet" type="button" disabled={busy} onClick={() => deleteRow("hours-delete", { id: hour.id, expected: { weekday: hour.weekday, opens_at: hour.opens_at, closes_at: hour.closes_at }, reason: "Admin xóa khung giờ theo cấu hình mới" })}>Xóa</button></div>)}<details className="admin-add-row"><summary>Thêm khung giờ</summary><RowForm action="hours-upsert" expectedValues={{}} onSubmit={onSubmit} busy={busy}><input type="hidden" name="id" value="" /><label>Thứ<select name="weekday" defaultValue="1">{[0, 1, 2, 3, 4, 5, 6].map((day) => <option key={day} value={day}>{day === 0 ? "Chủ nhật" : `Thứ ${day + 1}`}</option>)}</select></label><label>Mở cửa<input name="opensAt" type="time" defaultValue="10:00" required /></label><label>Đóng cửa<input name="closesAt" type="time" defaultValue="22:00" required /></label></RowForm></details></div><div className="admin-subsection"><h3>Ngày nghỉ</h3><div className="admin-list">{closures.map((closure) => <div className="admin-list-row" key={closure.closed_on}><RowForm action="closure-upsert" expectedValues={{}} onSubmit={onSubmit} busy={busy}><input type="hidden" name="closedOn" value={closure.closed_on} /><input type="hidden" name="previousReason" value={closure.reason} /><label>Ngày<input name="closedOnDisplay" type="date" defaultValue={closure.closed_on} disabled /></label><label>Lý do công khai<input name="closureReason" defaultValue={closure.reason} maxLength={500} required /></label></RowForm><button className="button button-quiet" type="button" disabled={busy} onClick={() => deleteRow("closure-delete", { closedOn: closure.closed_on, previousReason: closure.reason, reason: "Admin bỏ ngày nghỉ theo lịch mới" })}>Xóa</button></div>)}<details className="admin-add-row"><summary>Thêm ngày nghỉ</summary><RowForm action="closure-upsert" expectedValues={{}} onSubmit={onSubmit} busy={busy}><label>Ngày<input name="closedOn" type="date" required /></label><label>Lý do công khai<input name="closureReason" maxLength={500} required /></label></RowForm></details></div></div></Section>
    <Section eyebrow="Khu vực và bàn" title="Mặt bằng vận hành" note="Mã bàn và ID ổn định. Admin không bỏ qua quy trình occupied → cleaning → available."><div className="admin-list">{areas.map((area) => <RowForm key={area.id} action="area" expectedValues={{ name: area.name, is_active: area.is_active }} onSubmit={onSubmit} busy={busy}><input type="hidden" name="id" value={area.id} /><p className="admin-row-code">{area.code}</p><label>Tên khu vực<input name="name" defaultValue={area.name} maxLength={120} required /></label><label className="checkbox-label"><input name="isActive" type="checkbox" defaultChecked={area.is_active} /> Active</label></RowForm>)}</div><div className="admin-list">{tables.map((table) => <RowForm key={table.id} action="table" expectedValues={{ area_id: table.area_id, capacity: table.capacity, status: table.status, description: table.description, is_active: table.is_active }} onSubmit={onSubmit} busy={busy}><input type="hidden" name="id" value={table.id} /><p className="admin-row-code">{table.code} · {areaById.get(table.area_id)?.name ?? "—"}</p><input type="hidden" name="areaId" value={table.area_id} /><label>Khu vực (vị trí cố định)<select disabled defaultValue={table.area_id}>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select></label><label>Sức chứa<input name="capacity" type="number" min="1" max="8" defaultValue={table.capacity} required /></label><label>Trạng thái<select name="status" defaultValue={table.status}><option value="available" disabled={["occupied", "cleaning"].includes(table.status)}>available</option>{["occupied", "cleaning"].includes(table.status) && <option value={table.status}>{table.status}</option>}<option value="out_of_service" disabled={["occupied", "cleaning"].includes(table.status)}>out_of_service</option></select></label><label>Mô tả<input name="description" defaultValue={table.description} maxLength={500} required /></label><label className="checkbox-label"><input name="isActive" type="checkbox" defaultChecked={table.is_active} /> Active</label></RowForm>)}</div></Section>
    <Section eyebrow="Thực đơn" title="Catalogue live" note="Active quyết định có hiển thị; Available quyết định còn phục vụ. Combo vẫn là dữ liệu editorial riêng, không CRUD ở đây."><label className="admin-search">Tìm món<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Mã hoặc tên món" /></label><div className="admin-list">{categories.map((category) => <RowForm key={category.id} action="category" expectedValues={{ name: category.name, sort_order: category.sort_order, is_active: category.is_active }} onSubmit={onSubmit} busy={busy}><input type="hidden" name="id" value={category.id} /><label>Mã danh mục<strong className="admin-row-code">{category.code}</strong></label><label>Tên<input name="name" defaultValue={category.name} maxLength={120} required /></label><label>Thứ tự<input name="sortOrder" type="number" min="0" defaultValue={category.sort_order} required /></label><label className="checkbox-label"><input name="isActive" type="checkbox" defaultChecked={category.is_active} /> Active</label></RowForm>)}</div><div className="admin-menu-list">{filteredItems.map((item) => <details key={item.id}><summary><strong>{item.code}</strong> · {item.name} · {item.is_active ? "active" : "inactive"} · {item.is_available ? "đang phục vụ" : "tạm hết"}</summary><RowForm action="menu-item" expectedValues={{ category_id: item.category_id, name: item.name, description: item.description, price: Number(item.price), image_path: item.image_path, is_available: item.is_available, is_active: item.is_active, is_featured: item.is_featured, sort_order: item.sort_order }} onSubmit={onSubmit} busy={busy}><input type="hidden" name="id" value={item.id} /><label>Mã<strong className="admin-row-code">{item.code}</strong></label><label>Danh mục<select name="categoryId" defaultValue={item.category_id}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Tên<input name="name" defaultValue={item.name} maxLength={160} required /></label><label>Mô tả<textarea name="description" defaultValue={item.description} maxLength={500} required /></label><label>Giá (VND)<input name="price" type="number" min="0" step="1" defaultValue={Number(item.price)} required /></label><label>Ảnh catalogue<input name="imagePath" defaultValue={item.image_path ?? ""} placeholder="/images/menu/dishes/...webp" /></label><label>Thứ tự<input name="sortOrder" type="number" min="0" defaultValue={item.sort_order} required /></label><label className="checkbox-label"><input name="isAvailable" type="checkbox" defaultChecked={item.is_available} /> Đang phục vụ</label><label className="checkbox-label"><input name="isActive" type="checkbox" defaultChecked={item.is_active} /> Active public</label><label className="checkbox-label"><input name="isFeatured" type="checkbox" defaultChecked={item.is_featured} /> Nổi bật</label></RowForm></details>)}</div></Section>
    <Section eyebrow="Tài khoản" title="Quyền truy cập trusted" note="Không sửa auth.users, email hay mật khẩu. Không tự khóa/hạ quyền chính mình hoặc Admin active cuối cùng."><label className="admin-search">Tìm hồ sơ<input value={profileSearch} onChange={(event) => { setProfileSearch(event.target.value); setProfilePage(0); }} placeholder="Tên, số điện thoại hoặc role" /></label><TableWrap><thead><tr><th>Hồ sơ</th><th>Role</th><th>Active</th><th>Cập nhật quyền</th></tr></thead><tbody>{filteredProfiles.slice(profilePage * 25, (profilePage + 1) * 25).map((profile) => <tr key={profile.id}><td><strong>{profile.full_name || "Chưa đặt tên"}</strong><br /><span className="admin-muted">{profile.phone ?? "Không có số điện thoại"}</span></td><td><form id={`profile-${profile.id}`} onSubmit={(event) => onSubmit(event, "profile", { role: profile.role, is_active: profile.is_active })}><input type="hidden" name="id" value={profile.id} /><select aria-label={`Quyền ${profile.full_name || profile.id}`} name="role" defaultValue={profile.role}><option value="customer">customer</option><option value="staff">staff</option><option value="admin">admin</option></select></form></td><td><input form={`profile-${profile.id}`} name="isActive" type="checkbox" defaultChecked={profile.is_active} aria-label={`Active ${profile.full_name || profile.id}`} /></td><td><input form={`profile-${profile.id}`} name="reason" required maxLength={500} placeholder="Lý do" aria-label={`Lý do quyền ${profile.full_name || profile.id}`} /><button form={`profile-${profile.id}`} className="button button-quiet" type="submit" disabled={busy}>Lưu quyền</button></td></tr>)}</tbody></TableWrap><nav aria-label="Phân trang tài khoản" className="action-row"><button className="button button-secondary" disabled={profilePage === 0} onClick={() => setProfilePage(profilePage - 1)}>Trang trước</button><span>Trang {profilePage + 1} / {Math.max(1, Math.ceil(filteredProfiles.length / 25))} · {filteredProfiles.length} hồ sơ</span><button className="button button-secondary" disabled={(profilePage + 1) * 25 >= filteredProfiles.length} onClick={() => setProfilePage(profilePage + 1)}>Trang sau</button></nav></Section>
    <Section eyebrow="Audit" title="Dấu vết quản trị gần đây" note="Chỉ Admin đọc được. Chi tiết không chứa mật khẩu, JWT, cookie hoặc payload liên hệ đầy đủ."><TableWrap><thead><tr><th>Thời điểm</th><th>Actor</th><th>Đối tượng</th><th>Thao tác</th><th>Lý do</th></tr></thead><tbody>{audits.map((audit: AdminAudit) => <tr key={audit.id}><td>{new Date(audit.created_at).toLocaleString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" })}</td><td>{audit.actor_id ? audit.actor_id.slice(0, 8) : "system"}</td><td>{audit.entity_type} · {audit.entity_id.slice(0, 8)}</td><td>{audit.action}</td><td>{typeof audit.details.reason === "string" ? audit.details.reason : "—"}</td></tr>)}</tbody></TableWrap></Section>
  </div></section>;
}
