"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
type Table = { id: string; code: string; capacity: number; status: string };
export function StaffCreateBookingForm({ tables }: { tables: Table[] }) {
  const router = useRouter();
  const attempt = useRef<{ payload: string; key: string; startsAt: string } | null>(null);
  const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [source, setSource] = useState("phone");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const formElement = event.currentTarget; const form = new FormData(formElement); const date = String(form.get("date")); const time = String(form.get("time")); const body = { name: String(form.get("name")), phone: String(form.get("phone")), email: String(form.get("email") ?? ""), notes: String(form.get("notes") ?? ""), source: String(form.get("source")), startsAt: `${date}T${time}:00+07:00`, guestCount: Number(form.get("guestCount")), tableId: String(form.get("tableId")) }; const payload = JSON.stringify(body); if (!attempt.current || attempt.current.payload !== payload) attempt.current = { payload, key: crypto.randomUUID(), startsAt: body.source === "walk_in" ? new Date().toISOString() : body.startsAt }; const requestBody = { ...body, startsAt: attempt.current.startsAt, idempotencyKey: attempt.current.key }; try { const response = await fetch("/api/staff/bookings/create", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(requestBody) }); const result = await response.json().catch(() => null) as { bookingId?: string; message?: string } | null; setMessage(response.ok ? `Đã tạo booking ${result?.bookingId ?? ""}` : result?.message ?? "Chưa thể tạo booking."); if (response.ok) { formElement.reset(); attempt.current = null; router.refresh(); } } catch { setMessage("Không thể kết nối tới máy chủ."); } finally { setPending(false); } }
  return <section className="staff-section" aria-labelledby="staff-create-title"><div className="booking-section-heading"><div><p className="eyebrow">Phone / walk-in</p><h2 id="staff-create-title">Tạo booking tại nhà hàng.</h2></div><p className="section-note">Booking vận hành được xác nhận ngay nếu hợp lệ. Khách đến trực tiếp dùng thời điểm gửi yêu cầu; ngày/giờ chỉ áp dụng cho điện thoại.</p></div><form className="staff-create-form" onSubmit={submit}><label>Họ tên<input disabled={pending} name="name" required maxLength={120} /></label><label>Số điện thoại<input disabled={pending} name="phone" required maxLength={32} inputMode="tel" /></label><label>Email (nếu có)<input disabled={pending} name="email" type="email" maxLength={254} /></label><label>Nguồn<select disabled={pending} name="source" value={source} onChange={(event) => setSource(event.target.value)}><option value="phone">Điện thoại</option><option value="walk_in">Khách đến trực tiếp</option></select></label><label>Ngày<input name="date" type="date" required={source === "phone"} disabled={source === "walk_in" || pending} /></label><label>Giờ<input name="time" type="time" required={source === "phone"} disabled={source === "walk_in" || pending} step="60" /></label><label>Số khách<input disabled={pending} name="guestCount" type="number" min="1" max="8" required /></label><label>Bàn<select disabled={pending} name="tableId" required defaultValue=""> <option value="" disabled>Chọn bàn</option>{tables.filter((table) => table.status !== "out_of_service").map((table) => <option key={table.id} value={table.id}>{table.code} · {table.capacity} chỗ</option>)}</select></label><label className="staff-create-notes">Ghi chú<textarea disabled={pending} name="notes" maxLength={500} rows={3} /></label><button className="button button-primary" type="submit" disabled={pending}>{pending ? "Đang tạo…" : "Tạo booking"}</button><p className="staff-action-message" role={message && !message.startsWith("Đã") ? "alert" : "status"} aria-live="polite">{message}</p></form></section>;
}
