"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
type Props = { bookingId: string; status: string; tableId: string; tables: { id: string; code: string; capacity: number; status: string }[] };
const labels: Record<string, string> = { confirm: "Xác nhận", reject: "Từ chối", cancel: "Hủy booking", check_in: "Check-in", no_show: "Đánh dấu không đến", complete: "Hoàn tất phục vụ", move: "Đổi bàn" };
export function StaffActionPanel({ bookingId, status, tableId, tables }: Props) {
  const router = useRouter();
  const attempt = useRef<{ payload: string; requestId: string } | null>(null);
  const [guestConsent, setGuestConsent] = useState(false);
  const [pending, setPending] = useState(""); const [message, setMessage] = useState(""); const [reason, setReason] = useState(""); const [guestCount, setGuestCount] = useState(""); const [newTableId, setNewTableId] = useState(tableId);
  const availableTables = tables.filter((table) => table.status !== "out_of_service" || table.id === tableId);
  async function run(action: string) { if (["reject", "cancel", "no_show", "complete", "move"].includes(action) && !window.confirm(`${labels[action]}? Thao tác sẽ được ghi vào lịch sử vận hành.`)) return; setPending(action); setMessage(""); if (["reject", "cancel", "no_show", "move"].includes(action) && !reason.trim()) { setMessage("Hãy nhập lý do trước khi thực hiện."); setPending(""); return; } const payload = JSON.stringify({ id: bookingId, action, reason, guestConsent, actualGuestCount: guestCount ? Number(guestCount) : null, newTableId }); if (!attempt.current || attempt.current.payload !== payload) attempt.current = { payload, requestId: crypto.randomUUID() }; try { const response = await fetch("/api/staff/bookings/action", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...JSON.parse(payload), requestId: attempt.current.requestId }) }); const result = await response.json().catch(() => null) as { message?: string } | null; setMessage(response.ok ? "Đã cập nhật. Đang tải lại…" : result?.message ?? "Chưa thể hoàn tất thao tác."); setPending(""); if (response.ok || response.status === 409) router.refresh(); } catch { setPending(""); setMessage("Không thể kết nối tới máy chủ."); } }
  return <section className="staff-action-panel" aria-labelledby="staff-action-title"><h2 id="staff-action-title">Thao tác vận hành.</h2>{status === "pending" && <div className="staff-action-row"><button className="button button-primary" type="button" disabled={!!pending} onClick={() => void run("confirm")}>{pending === "confirm" ? "Đang xử lý…" : labels.confirm}</button><button className="button button-secondary" type="button" disabled={!!pending} onClick={() => void run("reject")}>{pending === "reject" ? "Đang xử lý…" : labels.reject}</button></div>}{["pending", "confirmed"].includes(status) && <button className="button button-secondary" type="button" disabled={!!pending} onClick={() => void run("cancel")}>{pending === "cancel" ? "Đang xử lý…" : labels.cancel}</button>}{status === "confirmed" && <div className="staff-action-row"><label>Số khách thực tế<input inputMode="numeric" type="number" min="1" max="8" value={guestCount} onChange={(event) => setGuestCount(event.target.value)} placeholder="Theo booking nếu để trống" /></label><button className="button button-primary" type="button" disabled={!!pending} onClick={() => void run("check_in")}>{pending === "check_in" ? "Đang xử lý…" : labels.check_in}</button><button className="button button-secondary" type="button" disabled={!!pending} onClick={() => void run("no_show")}>{pending === "no_show" ? "Đang xử lý…" : labels.no_show}</button></div>}{status === "checked_in" && <button className="button button-primary" type="button" disabled={!!pending} onClick={() => void run("complete")}>{pending === "complete" ? "Đang xử lý…" : labels.complete}</button>}{status === "confirmed" && <div className="staff-action-row"><label>Bàn mới<select value={newTableId} onChange={(event) => setNewTableId(event.target.value)}>{availableTables.map((table) => <option key={table.id} value={table.id}>{table.code} · {table.capacity} chỗ</option>)}</select></label><button className="button button-secondary" type="button" disabled={!!pending || newTableId === tableId || !guestConsent} onClick={() => void run("move")}>{pending === "move" ? "Đang xử lý…" : labels.move}</button><label><input type="checkbox" checked={guestConsent} onChange={(event) => setGuestConsent(event.target.checked)} />Khách đã đồng ý đổi bàn</label></div>}{["pending", "confirmed"].includes(status) && <label className="staff-reason">Lý do / ghi chú thao tác<textarea value={reason} onChange={(event) => setReason(event.target.value)} maxLength={500} rows={3} placeholder="Bắt buộc khi từ chối, hủy, đánh dấu không đến hoặc đổi bàn" /></label>}<p className="staff-action-message" aria-live="polite" role={message && !message.startsWith("Đã") ? "alert" : "status"}>{message}</p></section>;
}
