"use client";
import { useState } from "react";
type Table = { id: string; code: string; capacity: number; status: string; description: string };
const labels: Record<string, string> = { available: "Sẵn sàng", occupied: "Đang phục vụ", cleaning: "Cần dọn", out_of_service: "Tạm ngưng" };
export function StaffTableBoard({ initialTables }: { initialTables: Table[] }) {
  const [tables, setTables] = useState(initialTables); const [message, setMessage] = useState(""); const [pending, setPending] = useState("");
  async function markReady(id: string) { setPending(id); setMessage(""); try { const response = await fetch("/api/staff/tables/ready", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tableId: id }) }); const result = await response.json().catch(() => null) as { message?: string } | null; if (!response.ok) { setMessage(result?.message ?? "Chưa thể cập nhật bàn."); return; } setTables((current) => current.map((table) => table.id === id ? { ...table, status: "available" } : table)); setMessage("Đã đánh dấu bàn sẵn sàng."); } catch { setMessage("Không thể kết nối tới máy chủ."); } finally { setPending(""); } }
  return <section className="staff-section" aria-labelledby="staff-tables-title"><div className="booking-section-heading"><div><p className="eyebrow">Trạng thái vật lý</p><h2 id="staff-tables-title">Bàn trong nhà hàng.</h2></div><p className="section-note">Bàn cần dọn chỉ trở lại sẵn sàng sau thao tác xác nhận của Staff.</p></div><div className="staff-table-grid">{tables.map((table) => <article className={`staff-table-card status-${table.status}`} key={table.id}><div><p className="meta-line">{table.code} · {table.capacity} chỗ</p><h3>{labels[table.status] ?? table.status}</h3><p>{table.description || "Không có mô tả"}</p></div>{table.status === "cleaning" && <button className="button button-secondary" type="button" disabled={pending === table.id} onClick={() => void markReady(table.id)}>{pending === table.id ? "Đang xử lý…" : "Đã dọn xong"}</button>}</article>)}</div><p className="staff-action-message" role="status" aria-live="polite">{message}</p></section>;
}
