import type { Metadata } from "next";
import Link from "next/link";
import { connection } from "next/server";
import { redirect } from "next/navigation";
import { IdentityError, requireRole } from "@/lib/identity";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getStaffBookings, getStaffTables, staffStatusLabel, formatBookingDate } from "@/lib/staff-operations";
import { StaffCreateBookingForm } from "@/components/staff-create-booking-form";
import { StaffTableBoard } from "@/components/staff-table-board";
export const metadata: Metadata = { title: "Vận hành nhà hàng", robots: { index: false, follow: false } };
type Props = { searchParams: Promise<{ date?: string; status?: string; table?: string }> };
export default async function StaffPage({ searchParams }: Props) {
  const demo = process.env.NEXT_PUBLIC_STATIC_DEMO === "true"; if (demo) return <section className="section"><div className="site-container staff-container"><p className="eyebrow">Staff operations</p><h1>Vận hành nhà hàng.</h1><p className="lead">Bản GitHub Pages chỉ là demo tĩnh. Khu vực Staff chạy trên bản Vercel có Supabase.</p><Link className="button button-secondary" href="/">Về trang chính</Link></div></section>;
  await connection(); let identity;
  try { identity = await requireRole(["staff", "admin"]); } catch (error) { if (error instanceof IdentityError && error.status === 401) redirect("/login"); return <section className="section"><div className="site-container staff-container"><p className="eyebrow">Vận hành nhà hàng</p><h1>Không có quyền truy cập.</h1><p className="booking-error" role="alert">Chỉ tài khoản Staff hoặc Admin mới có thể sử dụng khu vực này.</p></div></section>; }
  const query = await searchParams; const supabase = await createSupabaseServerClient(); const [bookings, tables] = await Promise.all([getStaffBookings(supabase, { date: query.date, status: query.status, tableId: query.table }), getStaffTables(supabase)]);
  return <section className="section"><div className="site-container staff-container"><div className="section-heading"><div><p className="eyebrow">{identity.profile.role === "admin" ? "Admin · Staff operations" : "Staff operations"}</p><h1>Nhịp nhà hàng hôm nay.</h1></div><Link className="back-link" href="/">Về trang chính ↗</Link></div><form className="staff-filters" method="get"><label>Ngày<input type="date" name="date" defaultValue={query.date ?? ""} /></label><label>Trạng thái<select name="status" defaultValue={query.status ?? ""}><option value="">Tất cả trạng thái</option>{["pending", "confirmed", "checked_in", "completed", "cancelled", "rejected", "no_show"].map((status) => <option key={status} value={status}>{staffStatusLabel(status)}</option>)}</select></label><label>Bàn<select name="table" defaultValue={query.table ?? ""}><option value="">Tất cả bàn</option>{tables.map((table) => <option key={table.id} value={table.id}>{table.code}</option>)}</select></label><button className="button button-primary" type="submit">Lọc danh sách</button></form><div className="staff-summary"><p><strong>{bookings.length}</strong> booking trong kết quả</p><p><strong>{tables.filter((table) => table.status === "available").length}</strong> bàn sẵn sàng · <strong>{tables.filter((table) => table.status === "cleaning").length}</strong> bàn cần dọn</p></div><StaffTableBoard initialTables={tables} /><StaffCreateBookingForm tables={tables} /><section aria-labelledby="staff-bookings-title" className="staff-section"><div className="booking-section-heading"><div><p className="eyebrow">Danh sách công việc</p><h2 id="staff-bookings-title">Booking cần theo dõi.</h2></div><p className="section-note">Mỗi thao tác được kiểm tra lại bằng quyền Staff và đồng hồ database.</p></div>{bookings.length ? <div className="staff-booking-list">{bookings.map((booking) => <article className="staff-booking-row" key={booking.id}><div><p className="meta-line">{booking.table ? `${booking.table.code} · ${booking.table.capacity} chỗ · ${booking.source}` : "Bàn đang cập nhật"}</p><h3>{booking.contact_name}</h3><p>{formatBookingDate(booking.starts_at)} · {booking.guest_count} khách · <span className={`status status-${booking.status}`}>{staffStatusLabel(booking.status)}</span></p><p className="staff-contact">{booking.contact_phone}{booking.contact_email ? ` · ${booking.contact_email}` : ""}</p></div><Link className="text-link" href={`/staff/bookings/${booking.id}`}>Mở chi tiết</Link></article>)}</div> : <div className="empty-state"><h3>Không có booking phù hợp.</h3><p>Thử đổi ngày hoặc bộ lọc trạng thái.</p></div>}</section></div></section>;
}
